version: '3'

tasks:
  build:azuretools:
    dir: images/azuretools
    cmds:
      - |
        docker image build \
        -t oci.local/azuretools:latest \
        ./
  
  build:awstools:
    dir: images/awstools
    cmds:
      - |
        docker image build \
        -t oci.local/awstools:latest \
        ./

  build:azcopy:
    dir: images/azcopy
    cmds:
      - |
        docker image build \
        -t oci.local/azcopy:latest \
        ./

  build:atlantis:
    dir: images/atlantis
    cmds:
      - |
        docker image build \
        -t oci.local/atlantis:latest \
        ./

  build:kirocrew:
    dir: images/kirocrew
    cmds:
      - |
        docker image build \
        --build-arg VERSION="$(jq -r .version image-specs.json)" \
        --build-arg VCS_REF="$(git rev-parse HEAD)" \
        --build-arg BUILD_DATE="$(date -u +%Y-%m-%dT%H:%M:%SZ)" \
        -t oci.local/kirocrew:latest \
        ./