name: AWS infra-as-code container image
on:
  # release:
  #   types: [published, prereleased]
  push:
    branches:
      - main
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        image:
          - awstools
          - atlantis

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Get the version
        id: get_version
        run: echo "IMAGE_SPEC=$(jq -c . < images/${{ matrix.image }}/image-specs.json)" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/${{ matrix.image }}:cache
          cache-to: type=registry,ref=ghcr.io/${{ github.repository_owner }}/${{ matrix.image }}:cache
          context: ./images/${{ matrix.image }}
          file: ./images/${{ matrix.image }}/Dockerfile
          push: true
          # platforms: linux/amd64,linux/arm64
          platforms: linux/amd64
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ matrix.image }}:latest
            ghcr.io/${{ github.repository_owner }}/${{ matrix.image }}:${{ fromJson(env.IMAGE_SPEC).version }}
          labels: |
            org.opencontainers.image.description=Container image containing tools for infra-as-code pipelines to AWS.
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
            org.opencontainers.image.version=${{ fromJson(env.IMAGE_SPEC).version }}
